### ISSUE TITLE
Package Name

### ISSUE THREAD

**Issue by cortner** [cortner/MaterialsScienceTools.jl#2]
I am transitioning the package to v0.6, and will clean it up in the process.

I also want to take the opportunity to change the name of the package, as I find it long and unwieldy. The scope of the package will most likely be that we'll collect all sorts of codes that are useful for atomistic modelling of crystal elasticity and crystal defects: for now primarily the standard CLE boundary conditions, but as Julian's project progresses, I'd like to move those codes in here as well.

Any thoughts for scope and suggestions for a better package name?

CC @thudso @olso4056 @jjbraun @jameskermode

**Comment by cortner** [comment]
* `MaterialsScience.jl` : maybe too general.
* `MaterialDefects.jl` : maybe too specific
* `JuLIPMaterials.jl` : makes it clear it is part of the JuLIP eco-system

**Comment by cortner** [comment]
@thudso @olso4056 @jjbraun  FYI, this has been renamed now. From Julia REPL:
```
Pkg.rm("MaterialsScienceTools") 
Pkg.clone("https://github.com/cortner/JuLIPMaterials.jl.git")
```

(@jameskermode I assume you are not using this, so I'm letting you know just in case.)

**Comment by jameskermode** [comment]
I’m not but @lifelemons is
