### ISSUE TITLE
master branch to julia v0.6?

### ISSUE THREAD

**Issue by lifelemons** [cortner/MaterialsScienceTools.jl#6]
Hey,

So I made some tiny changes to some files to get the module working in v0.6. (i.e. it doesn't throw any errors when one loads it, `using MaterialsScienceTools`.

(I saw there is a 'cleanup' branch, but missing functionality, at least the bit I needed was in the master branch.)

So this modified version currently exist as a fork on my account (https://github.com/lifelemons/MaterialsScienceTools.jl), I was going to submit a pull request, but I think this should be on its own branch and not merged into the master. So the master retains v0.5 compatibility everything works as normal, and this new branch allows what is the essentially master branch to be, at least, loaded into v0.6 (and people can patch things if other functions fail in some other way)

Thoughts?

(I can also send the changes as a git patch, if that's easier)

**Comment by cortner** [comment]
oh no - did I forget to merge the `cleanup` branch? do you mind if I review what I have before merging? We may have to rebase your changes onto `cleanup`. I'll look at this asap!

**Comment by cortner** [comment]
what is missing in `cleanup` ?

**Comment by cortner** [comment]
I'm looking at your fork, and I think I did everything you did there as well. I'm really sorry you had to go through this by yourself. 

But I also tried to do a lot more, since there was so much duplicate functionality. (there is still some of that!) So I might have accidentally removed something you need. Do you have a notebook or script that I can try to get to run in order to make sure I have all the functionality you need?

**Comment by cortner** [comment]
The other thing that would be worthwhile doing now is for you to create a new branch, e.g. 'punit' that you can use to run whatever you need for now and we can clean up sometime in spring.

**Comment by cortner** [comment]
I've given you push access so you can just push the new branch to my repository

**Comment by lifelemons** [comment]
No worries! It wasn't much work as you've now seen.

Also saw that you merged cleanup -> master, I'll add the functions if they aren't there, you can then move then around if you want.

**Comment by cortner** [comment]
That would be great - thank you
